### ISSUE TITLE
Running into issues pulling historical SP+ data

### ISSUE THREAD

**Issue by rlindholm** [meysubb/cfbscrapR#13]
Calling cfb_sp_ranking with only a year parameter is throwing errors for me.

The code I ran to create the error: 

library(cfbscrapR)

sp_data <- data.frame()

for (year in 2005:2020){
  temp_df <- cfb_sp_ranking(year=year)
  sp_data <- rbind(temp_df, sp_data)
}

The trace:
Error in if (!repeated && grepl("%[[:xdigit:]]{2}", URL, useBytes = TRUE)) return(URL) : missing value where TRUE/FALSE needed
2.
URLencode(team, reserved = T)
1.
cfb_sp_ranking(year = year)

I'm not confident in R to be 100% positive that this is the issue, but I believe what this is saying is that, because I didn't pass in a team, team is set to null and can't be encoded. 

Potential Solutions:
Check to see if team is null before calling URLencode, if it is null, skip the encoding.

**Comment by meysubb** [comment]
Thanks for putting this in, will look at it soon.

**Comment by rlindholm** [comment]
I confirmed it, updating line 31 to this fixes the issue.

    if (!is.null(team)){
      team = URLencode(team, reserved = T)
      full_url = paste0(full_url,'&team=',team)
    }

**Comment by meysubb** [comment]
Sweet. I'll include this!

**Comment by meysubb** [comment]
Fixed this. Thanks for pointing this out!
