### ISSUE TITLE
cfb_play_stats_player() not working for all game IDs?

### ISSUE THREAD

**Issue by amicsta** [meysubb/cfbscrapR#17]
I installed the package, and was trying to pull the player stats using the various game IDs. But some work and some do not:

`cfb_play_stats_player(401012246)`
```
#Error in UseMethod("tbl_vars") : 
  no applicable method for 'tbl_vars' applied to an object of class "list"
```

**Comment by meysubb** [comment]
This is an issue with the underlying API. Take a look at this link:  https://api.collegefootballdata.com/play/stats?gameId=401012246

There is no data.

**Comment by meysubb** [comment]
This should be fixed now.
