### ISSUE TITLE
Getting Names Must be Unique Error when using cfb_pbp_data function

### ISSUE THREAD

**Issue by mcemerden** [meysubb/cfbscrapR#54]
I am getting this error when I am trying to get the pbp data for 2019. 

Error: Names must be unique.
x These names are duplicated:
  * "game_id" at locations 9 and 24.

I am using this code to get the data which worked for me previously. 

df <- cfb_pbp_data(year = 2019, season_type = "regular", week = NULL, epa_wpa = TRUE) %>% mutate(year = 2019)

R Version: 3.6.12

**Comment by spfleming** [comment]
Thanks for logging this! This is a known issue, and a reinstall of the package should fix it!

**Comment by meysubb** [comment]
Thanks for covering this Parker. I'm closing this issue.
